name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    - name: Install dev dependencies via pipenv
      run: |
        pipenv install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Format with Black
      run: |
        pipenv install black
        pipenv run python -m black .
        
    - name: PyCharm Python Security Scanner
      uses: tonybaloney/pycharm-security@1.22.2
